language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
    - os: linux
      sudo: required
      compiler: clang
    - os: osx

before_install:
  - ./.travis/before_install.sh

install:
  - cd $TRAVIS_BUILD_DIR
  - cmake .

script:
  - make -j2

notifications:
  irc:
    channels:
      - "irc.oftc.net#freerct"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch} - %{commit} - %{author}: %{message}"
      - "Build #%{build_number} - Details: %{build_url}"
    use_notice: true
    skip_join: true

env:
  global:
    secure: "gUgAXzGLyEkqSuMav5PLylFL3vtDO+TetIqzivkWDP5G6Md2W4xCSxBtgORtgOSngfJFipnoSvIzRo85ZyOJXKxN+1Ayy4D+xanFHpfY5pZtdhrpd9nbUXM/XLTJ9KeCd7n8BUq3Qd1h6cEAfCwvajSavC+bll3Df3MfSxISLdI="

addons:
  coverity_scan:
    project:
      name: "FreeRCT/FreeRCT"
      description: "Build from Travis-CI"
    build_command_prepend: "cmake ."
    build_command: "make -j2"
    notification_email: freerct@gmail.com
    branch_pattern: coverity
